development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: durst_portal_development
  #username: postgres
  #password: postgres
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: durst_portal_test
  #username: postgres
  #password: postgres
  pool: 5
